# Generated by Django 2.1.1 on 2018-09-30 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Interviewbook', '0005_auto_20180930_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewresponse',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
